language: node_js
node_js:
- '4'
branches:
  only:
  - master
cache:
  apt: true
  directories:
  - node_modules
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_ab963e00ecaf_key -iv $encrypted_ab963e00ecaf_iv
  -in .travis/id_rsa_docode.enc -out .travis/id_rsa_docode -d
#- openssl aes-256-cbc -K $encrypted_0fe06694a206_key -iv $encrypted_0fe06694a206_iv
#  -in .travis/id_rsa_qeio.enc -out ~\/.ssh/id_rsa_qeio -d
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
- chmod -R 600 .travis/id_rsa_docode
- eval $(ssh-agent)
- ssh-add .travis/id_rsa_docode
#- ssh-add ~/.ssh/id_rsa_qeio
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "jackLucky"
- git config --global user.email 262348314@qq.com
install:
- npm install
script:
- hexo clean && hexo g -d
